### ISSUE TITLE
Barman Issue

### ISSUE THREAD

**Issue by dbarajesh** [2ndquadrant-it/barman#105]
We are able to take full backup successfully but When ever we are trying to take incremental of remote master we are facing below issue?
Barman version is 1.6,PostgreSQL 9.4.

2017-05-10 20:47:11,182 [9744] barman.backup ERROR: Backup failed copying files
rsync: link_stat "/var/lib/pgsql/9.4/data/pg_subtrans/0E0B" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1505) [generator=3.0.6]

**Comment by dbarajesh** [comment]
Would appreciate with any pointers in this direction ..?
I am unable to figure out where the exact is the issue?

**Comment by mnencia** [comment]
Hi, this error is usually due to some issue communicating with the postgres host. 

Could you please paste the output of `barman diagnose`?

**Comment by hazbrose** [comment]
Hi,

Not wishing to hijack this issue, however I appear to be experiencing something similar when attempting to take an incremental of a standby:

`2018-01-03 22:00:51,575 [20810] barman.command_wrappers DEBUG: Command return code: 23`
`2018-01-03 22:00:51,576 [20810] barman.command_wrappers DEBUG: Command stdout:`
`2018-01-03 22:00:51,576 [20810] barman.command_wrappers DEBUG: Command stderr: rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118508" failed: No such file or directory (2)`
`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118511" failed: No such file or directory (2)`
`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118513" failed: No such file or directory (2)`
`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118615" failed: No such file or directory (2)`
`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118618" failed: No such file or directory (2)`
`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118620" failed: No such file or directory (2)`
`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1518) [Receiver=3.0.9]`
`2018-01-03 22:00:51,576 [20810] barman.copy_controller ERROR: First rsync error line: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1518) [Receiver=3.0.9]`

The ERROR line suggests that the first rsync error line is:

`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1518) [Receiver=3.0.9]`

Looking at the stderr DEBUG, the first line is:

`rsync: link_stat "/tblspc1/app_data_3/3/PG_9.4_201409291/16486/7118508" failed: No such file or directory (2)`

Admittedly, my python is very rusty these days, however it appears that the above line be ignored by the _rsync_ignore_vanished_files method within the copy_controller and is only being picked up due to the loop containing a continue rather than a break?

`def _rsync_ignore_vanished_files(self, rsync, *args, **kwargs):`
`"""`
`Wrap an Rsync.get_output() call and ignore missing args`
`TODO: when rsync 3.1 will be widespread, replace this`
`	with --ignore-missing-args argument`
`:param Rsync rsync: the Rsync object used to execute the copy`
`"""`
`kwargs['allowed_retval'] = (0, 23, 24)`
`rsync.get_output(*args, **kwargs)`
`\# If return code is 23 and there is any error which doesn't match`
`\# the VANISHED_RE regexp raise an error`
`if rsync.ret == 23 and rsync.err is not None:`
`	for line in rsync.err.splitlines():`
`		match = self.VANISHED_RE.match(line.rstrip())`
`		if match:`
`			continue     # <-- break here?????`
`		else:`
`			_logger.error("First rsync error line: %s", line)`
`			raise CommandFailedException(dict(`
`				ret=rsync.ret, out=rsync.out, err=rsync.err))`
`return rsync.out, rsync.err`

Barman 2.3.1
PostgreSQL 9.4
CentOS 7

Best wishes,
Harry

**Comment by mnencia** [comment]
This has already been resolved with https://github.com/2ndquadrant-it/barman/commit/46082da47fb95b149791c9de5926e823faa6d19a

**Comment by hazbrose** [comment]
Brilliant, thanks for the update.

Is there a projected release date for 2.4?
