### ISSUE TITLE
postgres.py: connection leak

### ISSUE THREAD

**Issue by mrechte** [2ndquadrant-it/barman#265]
Hello,
I think there is a connection leak in _cursor() method. I would rather code it like:

```
def _cursor(self, *args, **kwargs):

        """
        Return a cursor
        """
        if not self._conn:
             self.connect()
        return self._conn.cursor(*args, **kwargs)

```
Regards

**Comment by mnencia** [comment]
The semantic of PostgreSQL.connect() method is to do nothing if the connection is already opened and working correctly. Otherwise, it initializes another connection.

In other words, the existence of a pre-existent connection is checked by the self._check_connection() call inside the connect() method.
