### ISSUE TITLE
Timeline unawareness

### ISSUE THREAD

**Issue by gbartolini** [2ndquadrant-it/barman#31]
In case of timeline switch between two base backups, Barman is unable to follow the new timeline while associating WAL files to a backup.

A notable symptoms is that during "barman show-backup" the "Last available" WAL is not updated.

This issue might be related to #29

**Comment by vladimirfx** [comment]
+1 

More over, streaming WAL archiver incorrectly move to errors dir:
1. timeline history files created by pg_receivexlog
2. *.partial segments from previous timelines  (it should stay with .partial extension and archived as regular segments)

Timeline switch resulting in incorrect WAL archive state.
There is some explanation of pg_receivexlog behavior in context of timeline switch:
http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=0b6329130e8e4576e97ff763f0e773347e1a88af

I know that WAL streaming is new and experimental feature of barman 1.6.0 and can't replace 'normal' WAL archiving but described behavior can easily confuse DBA and unexpectedly increase RPO.

I've trying to fix streaming WAL archiver to align it with pg_receivexlog behavior but faced with difficulties because absent of some infrastructure in common archiving code. Nevertheless I've try to provide PR for this bug.

**Comment by vladimirfx** [comment]
More on this topic:
http://www.postgresql.org/message-id/50F56245.8050802@vmware.com

**Comment by gbartolini** [comment]
Fixed by 1f83e21818caa5991a8970c80a9a870c4348f5f8
