### ISSUE TITLE
Barman error folder

### ISSUE THREAD

**Issue by indreek** [2ndquadrant-it/barman#46]
Hi.

I have 6 files in barman error folder. 
- 00000003.history.20160705T220101Z.unknown
- 00000003.history.20160705T223501Z.unknown
- 00000003.history.20160705T225402Z.unknown
- 00000003.history.20160711T051405Z.unknown
- 00000003.history.20160711T111819Z.unknown
- 00000003.history.20160711T112704Z.unknown

All of them have similar content. Example vi 00000003.history.20160705T220101Z.unknown
has content "1       F9F/2861E770    before 2016-07-05 15:46:06.743379+03"

Barman check gives result 
archiver errors: FAILED (unknown: 6)

Where should i start looking for error? pg 9.5.3 barman 1.6.1

Thanks,
Indrek

**Comment by bjorand** [comment]
Same problem here with barman 2.0. I have deleted .unknown files and `barman check` is happy again.

**Comment by mnencia** [comment]
We need to better document the error folder mechanics. I'd like to implement a sub-command to inspect the content of the error directory and manipulate error files.

**Comment by takeda** [comment]
@mnencia until that feature is implemented, how can we analyze those files by hand?

**Comment by mnencia** [comment]
This is a quick explanation of possible content of the errors directory:

**.unknown**: Anything found under the `incoming` directory that doesn't match any known WAL file name is moved into the `errors` directory and renamed adding a timestamp and the `.unknown` suffix. This should not happen if everything is configured correctly.

**.duplicate**: When two different (not identical) WAL files with the same name are received, the second is moved into the `errors` directory and renamed adding a timestamp and the `.duplicate` suffix. This usually happens when more than one instance ships files into the same `incoming` directory. This is a grave error condition and can potentially generate unusable backups. 

When a file is found under the errors directory you should investigate the cause of the unexpected file and act accordingly.
Once the cause is fixed, you should move the error file away from the `errors` directory and execute another backup as soon as possible.

**Comment by martinmarques** [comment]
Should we close this? Is there anything else to do here?

**Comment by indreek** [comment]
We can close it.
