### ISSUE TITLE
How to verify backups?

### ISSUE THREAD

**Issue by alexmipego** [2ndquadrant-it/barman#47]
I'm still learning barman and postgres backups and I'm lost on how to validate that everything is running fine. I've everything setup with docker containers and cron jobs that run barman cron and barman backup every 1 and 15 minutes respectively.

Since the clusters are large (+- 50GB each) the backup part takes a long time and uses a lot of resources. So, after reading more docs I realized I don't need full backups every 15 minutes since the WAL files have everything for PITR, however I do not understand exactly how do you know if your "backup chain" is complete...

If I had barman backup running each 24h but I stopped barman for a few hours, and Postgres deleted some wal files, what happens when I restart barman? Will it warn me or let me know about the issue somehow?

If I understand it correctly, wal_keep_segments=150, would always keep 150 wal files just in case, but if postgres needed to create (eg) 200 WAL files it wouldn't keep the extra 50 right?

**Comment by snuxoll** [comment]
As far as I'm aware wal_keep_segments only affects replication, if your archive_command is failing because your server running barman is down PostgreSQL will continue to accumulate WAL segments until they are able to be successfully archived. Personal anectode: my barman server went down for a couple days without me noticing (bad, I know) because the disk used to store backups filled up, my databases then crashed because they ran out of space due to log segments not being archived.

**Comment by mnencia** [comment]
To early detect issues in your "backup chain" you should regularly run the `barman check all` command. It also has the `--nagios` option that produces a status line compatible with Nagios/Icinga.  Having a good alerting setup is required to avoid unnoticed failures!

I also advise you to write down a recovery procedure and test it regularly. It's the only way to be prepared in case of disaster.
